-- Durable operational observability for the T7 collector.
-- This migration does not alter existing T7 rows or adaptive checkpoints.

CREATE TABLE IF NOT EXISTS public.wingo_t7_poll_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_started_at TIMESTAMPTZ NOT NULL,
  poll_completed_at TIMESTAMPTZ,
  response_time_ms INTEGER,
  prediction_period TEXT,
  history_count INTEGER NOT NULL DEFAULT 0,
  oldest_history_period TEXT,
  newest_history_period TEXT,
  response_ok BOOLEAN NOT NULL DEFAULT FALSE,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wingo_t7_poll_audit_created_at
  ON public.wingo_t7_poll_audit (created_at DESC);

CREATE TABLE IF NOT EXISTS public.wingo_t7_pending_diagnostics (
  period_id TEXT PRIMARY KEY,
  signal TEXT,
  prediction_created_at TIMESTAMPTZ,
  first_seen_at TIMESTAMPTZ NOT NULL,
  last_seen_at TIMESTAMPTZ NOT NULL,
  state TEXT NOT NULL DEFAULT 'pending',
  provider_window_oldest_period TEXT,
  provider_window_newest_period TEXT,
  evidence JSONB,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wingo_t7_pending_diagnostics_state
  ON public.wingo_t7_pending_diagnostics (state, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS public.wingo_t7_gap_diagnostics (
  period TEXT PRIMARY KEY,
  type TEXT NOT NULL DEFAULT 'missing_t7',
  first_detected_at TIMESTAMPTZ NOT NULL,
  last_detected_at TIMESTAMPTZ NOT NULL,
  evidence JSONB,
  resolved BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wingo_t7_gap_diagnostics_open
  ON public.wingo_t7_gap_diagnostics (resolved, last_detected_at DESC);

COMMENT ON TABLE public.wingo_t7_poll_audit IS
  'One lightweight row per BDGTharu T7 poll; no full upstream payload is stored.';
COMMENT ON TABLE public.wingo_t7_pending_diagnostics IS
  'Operational pending/window-expiry state; source T7 rows remain immutable except for exact upstream updates.';
COMMENT ON TABLE public.wingo_t7_gap_diagnostics IS
  'Gaps observed inside the provider-returned T7 history sequence; never fabricated as T7 rows.';
